# Generated by Django 2.2.16 on 2022-01-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220118_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(max_length=6, null=True, verbose_name='Код подтверждения'),
        ),
    ]
