# Generated by Django 2.2.16 on 2022-01-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220118_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления'),
        ),
    ]
