# Generated by Django 2.2.16 on 2022-01-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220118_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(null=True, verbose_name='Код подтверждения'),
        ),
    ]
